program: main.py
method: grid
metric:
  name: val_f1
  goal: maximize

parameters:
  learning_rate:
    values: [0.00001, 0.00002, 0.00003, 0.000045]
  
  batch_size:
    value: 64

  temperature:
    value: 0.1

  dropout_rate:
    value: 0.10
  
  epochs:
    value: 100